name: Deploy App
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.11]
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pipx
        run: |
          pip install pipx
          pipx ensurepath
      - name: Install poetry
        run: pipx install poetry
      - name: Install dependencies
        run: poetry install --no-root
      - name: Test app
        run: poetry run pytest -v
      - name: Test linter
        run: poetry run flake8 .
      - name: Test mypy
        run: poetry run mypy .


