name: Deploy App
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install python 3.11
        run: sudo apt install python3.11
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install pipx
        run: sudo apt install pipx
      - name: Ensure pipx
        run: pipx ensurepath
      - name: Install poetry
        run: pipx install poetry
      - name: Install dependencies
        run: poetry install --no-root
      - name: Add environment
        run: poetry shell
      - name: Test app
        run: pytest -v
